---
- name: Converge
  hosts: all
  pre_tasks:
    - name: "Identify Hetzner Machine hostname (DNS)"
      # we are running on a hetzner machine and need a publicly accessible hostname
      # we can get it by reversing the ip4 address, prefixing it with static. and
      # suffixing it with clients.your-server.de
      set_fact:
        public_hostname: "static.{{ ansible_default_ipv4.address.split('.') | reverse | join('.') }}.clients.your-server.de"
  roles:
    - role: geerlingguy.docker
      become: true
    - role: ../../../.
      vars:
        # main configuration parameters
        registry_username: "{{ lookup('env','DOCKER_REGISTRY_USERNAME') }}"
        registry_password: "{{ lookup('env','DOCKER_REGISTRY_PASSWORD') }}"
        setup_database: true
        setup_wmc: true
        letsencrypt: true
        # do not issue certificates from production letsencrypt server
        letsencrypt_test: true
        secret_key: not-secret-at-all-but-okay-for-tests
        hostname: "{{ public_hostname }}"
        admin_email: admin@innoactive.de
        admin_password: sup3rs3cur3pa55w0rdf0rt3st1ng
        # change the default prefix to easily identify test containers / services
        hub_service_prefix: molecule_test_hub
