---
- name: Start Mailserver
  docker_container:
    name: "{{ container_names.mailserver }}"
    image: "{{ image_versions.mailserver }}"
    restart_policy: unless-stopped
    exposed_ports:
      - "1025"
    env:
      GMAIL_USER: "{{ mail_configuration.gmail.user }}"
      GMAIL_PASSWORD: "{{ mail_configuration.gmail.password }}"
      MAILNAME: "{{ hub_configuration.hostname }}"
      PORT: "1025"
    networks_cli_compatible: true
    networks:
      - name: "{{ network_names.main }}"
        aliases:
          - mailserver

- name: Create Hub database data volume
  docker_volume:
    name: "{{ volume_names.database }}"

- name: Start Database
  docker_container:
    name: "{{ container_names.database }}"
    image: "{{ image_versions.database }}"
    restart_policy: unless-stopped
    volumes:
      - "{{ volume_names.database }}:/var/lib/postgresql/data"
    networks_cli_compatible: true
    networks:
      - name: "{{ network_names.main }}"
        aliases:
          - db

- name: Start Message Queue
  docker_container:
    name: "{{ container_names.message_queue }}"
    image: "{{ image_versions.message_queue }}"
    restart_policy: unless-stopped
    networks_cli_compatible: true
    networks:
      - name: "{{ network_names.main }}"
        aliases:
          - redis
