---
- name: Create a volume to hold the certificates for TLS / SSL
  docker_volume:
    name: "{{ volume_names.tls_certificates }}"

- name: Start Reverse Proxy (nginx)
  docker_container:
    name: "{{ container_names.reverse_proxy }}"
    image: "{{ image_versions.reverse_proxy }}"
    restart_policy: unless-stopped
    published_ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - "{{ container_names.main }}"
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /docker-gen-templates
      - "{{ volume_names.tls_certificates }}:/etc/nginx/certs"
    networks_cli_compatible: true
    networks:
      - name: "{{ network_names.main }}"
        aliases:
          - nginx

- name: Start Reverse Proxy Auto-Configuration-Service
  docker_container:
    name: "{{ container_names.reverse_proxy_config_generator }}"
    image: "{{ image_versions.reverse_proxy_config_generator }}"
    restart_policy: unless-stopped
    command: >-
      -notify-sighup {{ container_names.reverse_proxy }} -watch -wait 5s:30s /docker-gen-templates/nginx.tmpl
      /etc/nginx/conf.d/default.conf
    volumes_from:
      - "{{ container_names.reverse_proxy }}"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks_cli_compatible: true
    networks:
      - name: "{{ network_names.main }}"
