name: Integration

on: [pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v1
    - name: Commit Linter
      uses: wagoid/commitlint-github-action@v1.3.1
      with:
        configFile: .commitlintrc.json

  test:

    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      INSTANCE_NAME_SUFFIX: -gh-action
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}

    steps:
    - uses: actions/checkout@v1
    # setup pipenv
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - uses: dschep/install-pipenv-action@v1
    - name: Install requirements using pipenv (system-wide)
      run: pipenv install --system
    - name: Test role using molecule
      run: molecule test
    - name: Test role (SAAS-Case) using molecule
      run: molecule test -s saas
    - name: Test role (with CIFS) using molecule
      run: molecule test -s with_cifs
